server:
  port: 3030
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.54:3306/smart_home?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: 1234
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml